### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by ekazakov** [rollbar/node_rollbar#101]
`unhandledRejection` are deprecated in Node 7

```
(node:55716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Client Params Error
(node:55716) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stclairdaniel** [comment]
Thanks for bringing this to our attention!

**Comment by lehresman** [comment]
I believe this is not a bug or issue with regard to Rollbar.  The problem is that your code has an unhandled rejection, and Node is telling you that in the future, this will cause a hard exit.

Rollbar actually solves this problem by catching any unhandled rejections if you configure it to do so.  See the README for details, but something like this should fix your problem:
```javascript
rollbar.handleUncaughtRejections("POST_SERVER_ITEM_ACCESS_TOKEN", options);
```

I created a simple example locally to demonstrate the problem:
```javascript
#!/usr/bin/env node
var rollbar = require("rollbar");
// rollbar.handleUncaughtRejections("[clip]");
new Promise(function(resolve, reject) {
    reject(new Error('woo'));
  });
```
With the `rollbar.handleUncaughtRejections` commented out, I get the following output:
```
$ node index.js 
(node:27892) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: woo
(node:27892) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

With it uncommented, the unhandled exception is captured by Rollbar and sent to my site with no warning from Node.

See this for more information about the warning message:
https://developers.redhat.com/blog/2016/11/09/node-7-and-promise-rejections-please-handle-them/
