### ISSUE TITLE
How to enable source maps?

### ISSUE THREAD

**Issue by piohhmy** [rollbar/node_rollbar#119]
Our node backend app uses webpack during compilation.  Is it possible for stack traces uploaded via node_rollbar to  use source maps?

**Comment by rivkahstandig3636** [comment]
Hi @piohhmy, yes, it is :) What issues are you having exactly? It may be easier to email us at support@rollbar.com rather than try to fix it through here.

**Comment by Ivshti** [comment]
@rivkahstandig3636 any updates on what was the issue?

I can and probably will write an email to support as well, but isn't it easier to have a clear flow of how sourcemaps are supposed to work with nodejs? 

For example:

1. When we receive stack traces, JS files seem to be referenced in the stack trace by their full path on the filesystem
2. When uploading sourcemaps, we should provide minified_url, and the http://... part does not really make sense with a nodejs app

Can you explain those details somewhere in the docs?

**Comment by piohhmy** [comment]
Response I received from support was source maps aren't supported with this lib yet.  I think there is some work going on to unify the JS rollbar lib and the node rollbar lib which may fix it going forward.

**Comment by Ivshti** [comment]
I was worried this could be a problem. As far as I can tell, because the local files do not have a full URL with hostname and etc., they cannot be mapped correctly to what we use to upload sourcemaps (minified_url)

Do you know any alternatives/workarounds that solve this issue?

**Comment by brianr** [comment]
Hi folks, Rollbar staff here. This is on our radar - it's going to require a little bit of work on our end for this to work nicely.

If you really really want to use source maps on the server-side now, you would do something like the following:

- include a `client` section in every payload to rollbar (sibling to `server`) that looks like: `client: {javascript: {source_map_enable: true, code_version: "the sha goes here"}}`
- transform your filenames to start with `http://` so we think they're URLs
- upload the source maps using our upload endpoint, using the same filenames as you transformed them to

I'd probably advise against this though because it feels really fragile.

**Comment by Ivshti** [comment]
Thanks for the quick response :)

it is really fragile, but it's definitely better than nothing. Currently, our use case is a bit different - we deploy a desktop application which uses node.js for a local server - we ship all of the code there minified, in a single fie. So having source-maps is very important in production.

But I guess the biggest question here is how to transform the filenames to start with `http://`. You mean rename the actual files?

**Comment by brianr** [comment]
@Ivshti No, not renaming the actual files. The approach I would take is to modify the code in node_rollbar that builds the `frames` part of the payload, to transform each filename (each frame is an object with a `filename` key) to start with `http://`. That code would go here: https://github.com/rollbar/node_rollbar/blob/master/lib/notifier.js#L135

Then, when you upload your source maps, the `minified_url`s would match the transformed filenames. Make sense?

(This is really only a constraint because our upload endpoint, and I think a few internal systems, expect the minified_url to be a url that starts with `http:` or `https:`.)

**Comment by Ivshti** [comment]
It does make sense, thanks; will try

**Comment by Ivshti** [comment]
So what I did as a start was: I added a simple option to be able to transform the frames being sent. It may be a hack, but it's clean-ish when it comes to the node_rollbar codebase itself - it just allows you to pass a generic function to transform the frames. May come in useful for other things too

https://github.com/Ivshti/node_rollbar/commit/73699c5a0b3198c91ec9f7eaea10b97cb3c91342

**Comment by Ivshti** [comment]
@brianr now I've got the sourcemaps uploaded, with the minified_url and code_version, and node_rollbar submitting errors for that particular file with that particular codeVersion. Still, it's not un-minifying the exceptions. How can I debug this?

**Comment by brianr** [comment]
Nicely done! I sent you a reply to your support request, but repeating the relevant info here...

The only thing you're missing is that you need the `client.javascript.code_version` and `client.javascript.source_map_enabled` keys in the payload. Probably the easiest way to do that would be to modify lib/notifier.js:buildBaseData as follows:

```
diff --git a/lib/notifier.js b/lib/notifier.js
index f5519f6..af46d75 100644
--- a/lib/notifier.js
+++ b/lib/notifier.js
@@ -75,6 +75,13 @@ function buildBaseData(extra) {
 
   if (SETTINGS.codeVersion) {
     data.code_version = SETTINGS.codeVersion;
+    // enable source maps
+    data.client = {
+      javascript: {
+        source_map_enabled: true,
+        code_version: SETTINGS.codeVersion
+      }
+    };
   }
 
   props = Object.getOwnPropertyNames(extra);
```
