### ISSUE TITLE
Improve rollbar.reportMessageWithPayloadData() interface

### ISSUE THREAD

**Issue by aristidesfl** [rollbar/node_rollbar#69]
Currently:

```
rollbar.reportMessage(message, level, request, callback)
rollbar.reportMessageWithPayloadData(message, {level: level, custom: payloadData} ,request, callback)`
```

Maybe it would make more sense:

```
rollbar.reportMessage(message, level, request, callback)
rollbar.reportMessageWithPayloadData(message, level, payloadData ,request, callback)
```

Still, `reportMessageWithPayloadData` would be a very long method name. 
`reportMessage` and `reportMessageWithPayloadData` could be merged together. When  payloadData exists to be passed, an empty object could be provided: 

```
rollbar.reportMessage(message, level, {} ,request, callback)
```

For more flexibility, the function could at the same time accept an object with all the parameters. This would allow fields to be omitted at will:

```
rollbar.reportMessage ({
    message: message,
    level: 'warning', 
    custom: {},
    request: request, 
    callback: function(){}
})
```

Thoughts?

**Comment by coryvirok** [comment]
Hi @aristidesfl and thanks for the feedback. This is a great idea and I think it will be more expressive once we move to the new notifier API like the rollbar-gem and rollbar.js repos have:

```js

import rollbar from 'rollbar';

rollbar.configure({accessToken: 'XXXXX', environment: 'development'});
rollbar.info('hello world');
rollbar.error('Some strange error', caughtError);
rollbar.error(caughtError, requestObject);
rollbar.error('Some strange error', caughtError, requestObject, callback);

// etc.
```

Would that syntax work for you?

**Comment by aristidesfl** [comment]
Looks like an improvment :+1:  
Is still there a way to pass custom data?

**Comment by aristidesfl** [comment]
rollbar.js seems great. I'm guessing it is not compatible with node..

**Comment by coryvirok** [comment]
You would pass custom data via `rollbar.info('hello world', {some: 'custom object'})` and we would know it's custom because it's not a:

- string - message
- request - Request object
- callback - function
- error - Error object

Unfortunately rollbar.js is not compatible with Node. There are just too many dissimilarities in the environment. It would be possible to create a shared library between the two project and then rollbar.js would contain the browser-specific code (which is considerable) and node_rollbar would have the Node specific code, (e.g. reading from the filesystem for code context in error frames.)

**Comment by aristidesfl** [comment]
puuuurfect, thanks for the quick reply :)

**Comment by rokob** [comment]
I am working on making https://github.com/rollbar/rollbar.js actually work on both the server and in the browser. The idea is to unify the APIs to handle this issue. The tracking issue for this work is: rollbar/rollbar.js#248
