### ISSUE TITLE
Invalid format. data.context object value found, but a null is required.

### ISSUE THREAD

**Issue by ronenteva** [rollbar/node_rollbar#73]
I receive the following error:
`Invalid format. data.context object value found, but a null is required.`
Looking at the content, I can see that:
`data.context: {}`

rollbar@0.5.12

**Comment by brianr** [comment]
Thanks @ronenteva for the report.

Note for us, or anyone who wants to take a stab at fixing this: looks like the relevant code in node_rollbar is https://github.com/rollbar/node_rollbar/blob/master/lib/notifier.js#L217-L225 . An empty object is not a valid context, per the API spec, so if the context would be `{}` then it should be either set to null or `delete`d.

**Comment by ronenteva** [comment]
Any update on the issue?

**Comment by maxcanna** [comment]
Same here on `"rollbar": "~0.5.14"`
Request data context:
```js
"context": {},
```

**Comment by Tapppi** [comment]
This seems to be quite a common occurrence for us as well.

**Comment by EragonJ** [comment]
I noticed this when registering an express error handler for upcoming errors.

```json
{
  "rollbar": "^0.6.2"
}
```

#### Calling sequence 

https://github.com/rollbar/node_rollbar/blob/65563ad171bdf8e6af4d02058ee83521eb57d39c/rollbar.js#L206
https://github.com/rollbar/node_rollbar/blob/65563ad171bdf8e6af4d02058ee83521eb57d39c/rollbar.js#L228
https://github.com/rollbar/node_rollbar/blob/65563ad171bdf8e6af4d02058ee83521eb57d39c/lib/notifier.js#L462

**Comment by ronenteva** [comment]
@brianr any updates?

**Comment by gvilarino** [comment]
Bump! Any updates?

It's really troublesome that a format conflict that could be addressed transparently by the lib is making servers crash...

**Comment by lehresman** [comment]
Actually, it looks like "context" is expected to be a string, according to https://rollbar.com/docs/api/items_post/:
```javascript
    // Optional: context
    // An identifier for which part of your application this event came from.
    // Items can be searched by context (prefix search)
    // For example, in a Rails app, this could be `controller#action`.
    // In a single-page javascript app, it could be the name of the current screen or route.
    "context": "project#index",
```

This error seems to be thrown if ANY object value is passed as the context, not just an empty object as @brianr suggested.  

There are two solutions I can see, each has pros and cons:

1.  Serialize objects with `JSON.stringify`/`stringify` if an object passed as a context.  This would not lose any data, and would probably be the most expected behavior.  However, it could be quite large if a large object was accidentally passed in as the context.
2. Just set the context to null if an object is passed in, since it's not supposed to be an object.  The problem here is that this would be silent, lossy behavior.  If they intended to pass an object and we just nullify it, they may be confused why it didn't come through to Rollbar.

**Comment by rokob** [comment]
How is this getting set in the first place? Are people setting it themselves to `{}` or `{some: "object"}` or is there some library code that is incorrectly setting it?

**Comment by lehresman** [comment]
I'm not sure.  Either way, it seems like the `node_rollbar` sdk should be smart enough to handle the situation gracefully.

**Comment by rokob** [comment]
Well I wanted to rule out some bug in the notifier itself causing this, but that doesn't seem to be the case. I feel like we could just move the context value to custom data and set it to null if it is not a string.

**Comment by lehresman** [comment]
Note for posterity:  We had an internal discussion about this and decided to serialize `data.context` if an object is detected.  Since context has special internal meaning to Rollbar, it didn't seem like the best option to move it to the custom attribute.
