### ISSUE TITLE
crypto not usable, falling back to insecure Math.random()

### ISSUE THREAD

**Issue by callumacrae** [rollbar/node_rollbar#82]
I'm using Node 4.2.1, and requiring the rollbar package causes the following to be outputting:

```
[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```

What can I do to fix this?

**Comment by Crisfole** [comment]
Hey Callum, it looks looks like node-uuid added that warning in Nov. last year:

https://github.com/broofa/node-uuid/commit/c9760f931d36bf01143dd2a78110ca05061e39e7

Since we're not using the UUIDs for security purposes it's not really an issue, but clearing security warnings is a Good Thing™...

What version of node-uuid do you have installed at the moment? (It looks like there's been a bunch of work around that line of code lately that makes it pointless to try and guess what actual code is being run on your end). `npm list node-uuid` should do the trick...

**Comment by callumacrae** [comment]
```
├─┬ rollbar@0.5.16
│ └── node-uuid@1.4.7
```

It's used by a few of my deps, and all of them are 1.4.7.

**Comment by Crisfole** [comment]
Great, thanks! I'm a bit confused, this is the node_rollbar repo, but the only place that warning is printed is if `window` is defined (which isn't the case in node). Do you have a global `window` variable defined somewhere that's causing `setupBrowser` code to be called?

Also, when you `require('crypto')` does it work for you?

**Comment by callumacrae** [comment]
Oh! `global.window` is being defined to get some server-side React stuff working. I guess that's what's causing the problem, then!

**Comment by Crisfole** [comment]
K, great! Thanks for reporting anyway!

**Comment by crusaderltd** [comment]
@callumacrae I have the same issue... Using React server rendering and need to add `if (typeof window === 'undefined') { global.window = {} }`. I'm getting `[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()` in the console now. 

I'm using `node-uuid` (`uuid.v4()`) for the `genid` method of `express-session`.

Not a rollbar issue - but do you know of any way to avoid this..?

**Comment by callumacrae** [comment]
I moved the `global.window` declaration into the function I'm calling react from, instead of defining it on app start-up time. Solved a couple other problems as well.
